[package]
name = "my_starknet_project"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.4.0"

[[target.starknet-contract]]
build-external-contract-artifacts = ["sierra", "casm"]
sierra = true
casm = true


[tool.snforge]